version: '3.8'

services:
  # フロントエンド (Nginx配信)
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "80:80"
    restart: always

  # バックエンド (FastAPI)
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      # DBデータのみをホスト側と同期して消えないようにする
      - ./backend/homestocker.db:/app/homestocker.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
    restart: always